import 'package:uuid/uuid.dart';

class MedicineModel {
  final String id;
  final String name;
  final String genericName;
  final String category;
  final String manufacturer;
  final String strength;
  final String unit;
  final double price;
  final double costPrice;
  final int stockQuantity;
  final int minStockAlert;
  final String? imageUrl;
  final bool requiresPrescription;
  final String description;
  final String dosageInstructions;
  final DateTime createdAt;
  final DateTime updatedAt;

  MedicineModel({
    String? id,
    required this.name,
    this.genericName = '',
    this.category = 'Tablet',
    this.manufacturer = '',
    this.strength = '',
    this.unit = 'Strip (10 pcs)',
    required this.price,
    this.costPrice = 0.0,
    this.stockQuantity = 0,
    this.minStockAlert = 10,
    this.imageUrl,
    this.requiresPrescription = false,
    this.description = '',
    this.dosageInstructions = '',
    DateTime? createdAt,
    DateTime? updatedAt,
  })  : id = id ?? const Uuid().v4(),
        createdAt = createdAt ?? DateTime.now(),
        updatedAt = updatedAt ?? DateTime.now();

  bool get isOutOfStock => stockQuantity <= 0;
  bool get isLowStock => stockQuantity > 0 && stockQuantity <= minStockAlert;

  MedicineModel copyWith({
    String? id,
    String? name,
    String? genericName,
    String? category,
    String? manufacturer,
    String? strength,
    String? unit,
    double? price,
    double? costPrice,
    int? stockQuantity,
    int? minStockAlert,
    String? imageUrl,
    bool? requiresPrescription,
    String? description,
    String? dosageInstructions,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return MedicineModel(
      id: id ?? this.id,
      name: name ?? this.name,
      genericName: genericName ?? this.genericName,
      category: category ?? this.category,
      manufacturer: manufacturer ?? this.manufacturer,
      strength: strength ?? this.strength,
      unit: unit ?? this.unit,
      price: price ?? this.price,
      costPrice: costPrice ?? this.costPrice,
      stockQuantity: stockQuantity ?? this.stockQuantity,
      minStockAlert: minStockAlert ?? this.minStockAlert,
      imageUrl: imageUrl ?? this.imageUrl,
      requiresPrescription: requiresPrescription ?? this.requiresPrescription,
      description: description ?? this.description,
      dosageInstructions: dosageInstructions ?? this.dosageInstructions,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? DateTime.now(),
    );
  }

  factory MedicineModel.fromMap(Map<String, dynamic> map) {
    return MedicineModel(
      id: map['id']?.toString() ?? const Uuid().v4(),
      name: map['name']?.toString() ?? '',
      genericName: map['generic_name']?.toString() ?? '',
      category: map['category']?.toString() ?? 'Tablet',
      manufacturer: map['manufacturer']?.toString() ?? '',
      strength: map['strength']?.toString() ?? '',
      unit: map['unit']?.toString() ?? 'Strip',
      price: (map['price'] as num?)?.toDouble() ?? 0.0,
      costPrice: (map['cost_price'] as num?)?.toDouble() ?? 0.0,
      stockQuantity: (map['stock_quantity'] as num?)?.toInt() ?? 0,
      minStockAlert: (map['min_stock_alert'] as num?)?.toInt() ?? 10,
      imageUrl: map['image_url']?.toString(),
      requiresPrescription: map['requires_prescription'] == true,
      description: map['description']?.toString() ?? '',
      dosageInstructions: map['dosage_instructions']?.toString() ?? '',
      createdAt: map['created_at'] != null
          ? DateTime.tryParse(map['created_at'].toString()) ?? DateTime.now()
          : DateTime.now(),
      updatedAt: map['updated_at'] != null
          ? DateTime.tryParse(map['updated_at'].toString()) ?? DateTime.now()
          : DateTime.now(),
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'name': name,
      'generic_name': genericName,
      'category': category,
      'manufacturer': manufacturer,
      'strength': strength,
      'unit': unit,
      'price': price,
      'cost_price': costPrice,
      'stock_quantity': stockQuantity,
      'min_stock_alert': minStockAlert,
      'image_url': imageUrl,
      'requires_prescription': requiresPrescription,
      'description': description,
      'dosage_instructions': dosageInstructions,
      'created_at': createdAt.toIso8601String(),
      'updated_at': updatedAt.toIso8601String(),
    };
  }
  /// Initial sample medicines for testing and demo display
  static List<MedicineModel> get sampleMedicines => [
        MedicineModel(
          id: 'med-001',
          name: 'Napa 500mg',
          genericName: 'Paracetamol',
          category: 'Tablet',
          manufacturer: 'Beximco Pharmaceuticals PLC',
          strength: '500 mg',
          unit: 'Strip (10 pcs)',
          price: 12.0,
          costPrice: 10.8,
          stockQuantity: 150,
          minStockAlert: 25,
          imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80',
          requiresPrescription: false,
          description: 'Fast-acting antipyretic and analgesic for fever, mild to moderate headache, muscle pain, and toothache.',
          dosageInstructions: '1 to 2 tablets every 4 to 6 hours as needed. Maximum 8 tablets in 24 hours.',
        ),
        MedicineModel(
          id: 'med-002',
          name: 'Alatrol',
          genericName: 'Cetirizine',
          category: 'Tablet',
          manufacturer: 'Square Pharmaceuticals PLC',
          strength: '10 mg',
          unit: 'Strip (10 pcs)',
          price: 35.0,
          costPrice: 31.5,
          stockQuantity: 120,
          minStockAlert: 20,
          imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80',
          requiresPrescription: false,
          description: 'Second-generation antihistamine for seasonal allergic rhinitis, sneezing, runny nose, and chronic urticaria.',
          dosageInstructions: '1 tablet (10mg) once daily with water.',
        ),
        MedicineModel(
          id: 'med-003',
          name: 'Monas 10',
          genericName: 'Montelukast',
          category: 'Tablet',
          manufacturer: 'The ACME Laboratories Ltd.',
          strength: '10 mg',
          unit: 'Strip (10 pcs)',
          price: 175.0,
          costPrice: 157.5,
          stockQuantity: 80,
          minStockAlert: 15,
          imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80',
          requiresPrescription: true,
          description: 'Leukotriene receptor antagonist for prophylaxis and chronic treatment of bronchial asthma and allergic rhinitis.',
          dosageInstructions: '1 tablet daily in the evening at bedtime.',
        ),
        MedicineModel(
          id: 'med-004',
          name: 'A-Fenac 50',
          genericName: 'Aceclofenac',
          category: 'Tablet',
          manufacturer: 'The ACME Laboratories Ltd.',
          strength: '50 mg',
          unit: 'Strip (10 pcs)',
          price: 40.0,
          costPrice: 36.0,
          stockQuantity: 90,
          minStockAlert: 15,
          imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80',
          requiresPrescription: true,
          description: 'Non-steroidal anti-inflammatory drug (NSAID) for relief of pain and inflammation in osteoarthritis and rheumatoid arthritis.',
          dosageInstructions: '1 tablet twice daily, preferably with or immediately after food.',
        ),
        MedicineModel(
          id: 'med-005',
          name: 'Pantonix 20',
          genericName: 'Pantoprazole',
          category: 'Tablet',
          manufacturer: 'Incepta Pharmaceuticals Ltd.',
          strength: '20 mg',
          unit: 'Strip (10 pcs)',
          price: 80.0,
          costPrice: 72.0,
          stockQuantity: 110,
          minStockAlert: 20,
          imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80',
          requiresPrescription: false,
          description: 'Proton pump inhibitor indicated for peptic ulcer, gastroesophageal reflux disease (GERD), and acid hypersecretion.',
          dosageInstructions: '1 tablet once daily 30 minutes before breakfast with a glass of water.',
        ),
        MedicineModel(
          id: 'med-006',
          name: 'Sergel 20',
          genericName: 'Esomeprazole',
          category: 'Capsule',
          manufacturer: 'Healthcare Pharmaceuticals Ltd.',
          strength: '20 mg',
          unit: 'Strip (10 pcs)',
          price: 70.0,
          costPrice: 63.0,
          stockQuantity: 130,
          minStockAlert: 20,
          imageUrl: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=500&auto=format&fit=crop&q=80',
          requiresPrescription: false,
          description: 'Superior acid suppression for GERD, erosive esophagitis, and prevention of NSAID-associated gastric ulcers.',
          dosageInstructions: '1 capsule once daily 30-60 minutes before morning meal.',
        ),
        MedicineModel(
          id: 'med-007',
          name: 'Maxpro 20',
          genericName: 'Esomeprazole',
          category: 'Capsule',
          manufacturer: 'Square Pharmaceuticals PLC',
          strength: '20 mg',
          unit: 'Strip (10 pcs)',
          price: 70.0,
          costPrice: 63.0,
          stockQuantity: 140,
          minStockAlert: 20,
          imageUrl: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=500&auto=format&fit=crop&q=80',
          requiresPrescription: false,
          description: 'Effective proton pump inhibitor capsule for chronic acidity, heartburn, and stomach ulcer healing.',
          dosageInstructions: '1 capsule once daily 30 minutes before meal.',
        ),
        MedicineModel(
          id: 'med-008',
          name: 'Seclo 20',
          genericName: 'Omeprazole',
          category: 'Capsule',
          manufacturer: 'Square Pharmaceuticals PLC',
          strength: '20 mg',
          unit: 'Strip (10 pcs)',
          price: 60.0,
          costPrice: 54.0,
          stockQuantity: 160,
          minStockAlert: 25,
          imageUrl: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=500&auto=format&fit=crop&q=80',
          requiresPrescription: false,
          description: 'Trusted proton pump inhibitor for treatment of gastric and duodenal ulcers, gastritis, and acid indigestion.',
          dosageInstructions: '1 capsule once daily before breakfast.',
        ),
        MedicineModel(
          id: 'med-009',
          name: 'Axet 500',
          genericName: 'Cefuroxime Axetil',
          category: 'Capsule',
          manufacturer: 'Square Pharmaceuticals PLC',
          strength: '500 mg',
          unit: 'Strip (10 pcs)',
          price: 500.0,
          costPrice: 450.0,
          stockQuantity: 50,
          minStockAlert: 10,
          imageUrl: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=500&auto=format&fit=crop&q=80',
          requiresPrescription: true,
          description: 'Second-generation cephalosporin antibiotic for respiratory tract infections, ENT infections, and urinary tract infections.',
          dosageInstructions: '1 capsule twice daily after meals for 5 to 7 days as prescribed.',
        ),
        MedicineModel(
          id: 'med-010',
          name: 'Indomet 25',
          genericName: 'Indomethacin',
          category: 'Capsule',
          manufacturer: 'Beximco Pharmaceuticals PLC',
          strength: '25 mg',
          unit: 'Strip (10 pcs)',
          price: 30.0,
          costPrice: 27.0,
          stockQuantity: 75,
          minStockAlert: 15,
          imageUrl: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=500&auto=format&fit=crop&q=80',
          requiresPrescription: true,
          description: 'Potent NSAID indicated for moderate to severe osteoarthritis, rheumatoid arthritis, and acute gouty arthritis.',
          dosageInstructions: '1 capsule 2 to 3 times daily with food or antacid.',
        ),
        MedicineModel(
          id: 'med-011',
          name: 'Tusca Plus Syrup',
          genericName: 'Guaifenesin + Levomenthol + Diphenhydramine',
          category: 'Syrup',
          manufacturer: 'Square Pharmaceuticals PLC',
          strength: '(100mg + 1.1mg + 14mg) / 5ml',
          unit: 'Bottle (100ml)',
          price: 85.0,
          costPrice: 76.5,
          stockQuantity: 85,
          minStockAlert: 15,
          imageUrl: 'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=500&auto=format&fit=crop&q=80',
          requiresPrescription: false,
          description: 'Triple-action expectorant syrup that loosens mucus, relieves nasal congestion, and soothes irritating cough.',
          dosageInstructions: 'Adults: 10 ml (2 teaspoonfuls) 3 times daily after meals.',
        ),
        MedicineModel(
          id: 'med-012',
          name: 'Omidon Syrup',
          genericName: 'Domperidone',
          category: 'Syrup',
          manufacturer: 'Incepta Pharmaceuticals Ltd.',
          strength: '5 mg / 5 ml',
          unit: 'Bottle (100ml)',
          price: 60.0,
          costPrice: 54.0,
          stockQuantity: 70,
          minStockAlert: 15,
          imageUrl: 'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=500&auto=format&fit=crop&q=80',
          requiresPrescription: false,
          description: 'Prokinetic suspension syrup for nausea, vomiting, epigastric bloating, and gastrointestinal motility disorders.',
          dosageInstructions: '10-20 ml 3 times daily 15-30 minutes before meals.',
        ),
        MedicineModel(
          id: 'med-013',
          name: 'Adryl Syrup',
          genericName: 'Diphenhydramine Hydrochloride',
          category: 'Syrup',
          manufacturer: 'Square Pharmaceuticals PLC',
          strength: '12.5 mg / 5 ml',
          unit: 'Bottle (100ml)',
          price: 45.0,
          costPrice: 40.5,
          stockQuantity: 65,
          minStockAlert: 12,
          imageUrl: 'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=500&auto=format&fit=crop&q=80',
          requiresPrescription: false,
          description: 'Antihistaminic cough syrup for allergic cough, sneezing, watery eyes, and nighttime dry cough.',
          dosageInstructions: '10 ml 3 to 4 times daily.',
        ),
        MedicineModel(
          id: 'med-014',
          name: 'Ambrolit Syrup',
          genericName: 'Ambroxol Hydrochloride',
          category: 'Syrup',
          manufacturer: 'Beximco Pharmaceuticals PLC',
          strength: '15 mg / 5 ml',
          unit: 'Bottle (100ml)',
          price: 65.0,
          costPrice: 58.5,
          stockQuantity: 80,
          minStockAlert: 15,
          imageUrl: 'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=500&auto=format&fit=crop&q=80',
          requiresPrescription: false,
          description: 'Mucolytic expectorant that thins thick bronchial secretions and facilitates easy coughing out.',
          dosageInstructions: '10 ml 3 times daily after meals.',
        ),
        MedicineModel(
          id: 'med-015',
          name: 'Brozedex Syrup',
          genericName: 'Bromhexine + Menthol',
          category: 'Syrup',
          manufacturer: 'Incepta Pharmaceuticals Ltd.',
          strength: '4 mg / 5 ml',
          unit: 'Bottle (100ml)',
          price: 60.0,
          costPrice: 54.0,
          stockQuantity: 60,
          minStockAlert: 12,
          imageUrl: 'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=500&auto=format&fit=crop&q=80',
          requiresPrescription: false,
          description: 'Bronchial secretolytic syrup that liquefies tenacious mucus and provides soothing cooling relief.',
          dosageInstructions: '10 ml 3 times daily.',
        ),
        MedicineModel(
          id: 'med-016',
          name: 'Ace Suspension',
          genericName: 'Paracetamol',
          category: 'Suspension',
          manufacturer: 'Square Pharmaceuticals PLC',
          strength: '120 mg / 5 ml',
          unit: 'Bottle (60ml)',
          price: 35.0,
          costPrice: 32.2,
          stockQuantity: 95,
          minStockAlert: 20,
          imageUrl: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=500&auto=format&fit=crop&q=80',
          requiresPrescription: false,
          description: 'Pediatric paracetamol suspension for prompt reduction of high fever, teething pain, and immunization reactions.',
          dosageInstructions: 'Dosage based on child weight/age (typically 5-10 ml every 4-6 hours).',
        ),
        MedicineModel(
          id: 'med-017',
          name: 'Ciprocin Suspension',
          genericName: 'Ciprofloxacin',
          category: 'Suspension',
          manufacturer: 'Square Pharmaceuticals PLC',
          strength: '250 mg / 5 ml',
          unit: 'Bottle (60ml)',
          price: 85.0,
          costPrice: 76.5,
          stockQuantity: 45,
          minStockAlert: 10,
          imageUrl: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=500&auto=format&fit=crop&q=80',
          requiresPrescription: true,
          description: 'Broad-spectrum fluoroquinolone antibiotic suspension for gastrointestinal, enteric, and urinary infections.',
          dosageInstructions: 'As directed by physician, usually twice daily for 5-7 days.',
        ),
        MedicineModel(
          id: 'med-018',
          name: 'Cef-3 Suspension',
          genericName: 'Cefixime',
          category: 'Suspension',
          manufacturer: 'Square Pharmaceuticals PLC',
          strength: '100 mg / 5 ml',
          unit: 'Bottle (50ml)',
          price: 210.0,
          costPrice: 189.0,
          stockQuantity: 55,
          minStockAlert: 12,
          imageUrl: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=500&auto=format&fit=crop&q=80',
          requiresPrescription: true,
          description: 'Third-generation cephalosporin antibiotic suspension for acute otitis media, pharyngitis, and enteric fever.',
          dosageInstructions: '8 mg/kg daily as a single dose or divided into two doses.',
        ),
        MedicineModel(
          id: 'med-019',
          name: 'Antanil Plus Suspension',
          genericName: 'Aluminum Hydroxide + Magnesium Hydroxide + Simethicone',
          category: 'Suspension',
          manufacturer: 'Ibn Sina Pharmaceutical Industry Ltd.',
          strength: 'Regular Antacid Spec',
          unit: 'Bottle (200ml)',
          price: 95.0,
          costPrice: 85.5,
          stockQuantity: 75,
          minStockAlert: 15,
          imageUrl: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=500&auto=format&fit=crop&q=80',
          requiresPrescription: false,
          description: 'Fast-acting pleasant-tasting antacid suspension for relief of hyperacidity, gas flatulence, and heartburn.',
          dosageInstructions: '2 to 4 teaspoonfuls (10-20ml) 20 minutes to 1 hour after meals and at bedtime.',
        ),
        MedicineModel(
          id: 'med-020',
          name: 'Zithrin Suspension',
          genericName: 'Azithromycin',
          category: 'Suspension',
          manufacturer: 'Beximco Pharmaceuticals PLC',
          strength: '200 mg / 5 ml',
          unit: 'Bottle (35ml)',
          price: 150.0,
          costPrice: 135.0,
          stockQuantity: 60,
          minStockAlert: 12,
          imageUrl: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=500&auto=format&fit=crop&q=80',
          requiresPrescription: true,
          description: 'Macrolide antibiotic suspension for pediatric upper and lower respiratory tract infections and tonsillitis.',
          dosageInstructions: '10 mg/kg once daily for 3 days 1 hour before or 2 hours after meals.',
        ),
        MedicineModel(
          id: 'med-021',
          name: 'Seclo IV',
          genericName: 'Omeprazole',
          category: 'Injection',
          manufacturer: 'Square Pharmaceuticals PLC',
          strength: '40 mg / vial',
          unit: 'Vial / Ampoule',
          price: 95.0,
          costPrice: 80.2,
          stockQuantity: 40,
          minStockAlert: 10,
          imageUrl: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=500&auto=format&fit=crop&q=80',
          requiresPrescription: true,
          description: 'Intravenous proton pump inhibitor for severe gastrointestinal bleeding, peptic ulceration, and pre-surgery prophylaxis.',
          dosageInstructions: 'Administered as slow IV injection over 5 minutes by healthcare professionals.',
        ),
        MedicineModel(
          id: 'med-022',
          name: 'Pantogut IV',
          genericName: 'Pantoprazole',
          category: 'Injection',
          manufacturer: 'Beximco Pharmaceuticals PLC',
          strength: '40 mg / vial',
          unit: 'Vial / Ampoule',
          price: 90.0,
          costPrice: 81.0,
          stockQuantity: 45,
          minStockAlert: 10,
          imageUrl: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=500&auto=format&fit=crop&q=80',
          requiresPrescription: true,
          description: 'Injectable pantoprazole for hospital treatment of acute gastroesophageal reflux and ulcer bleeding.',
          dosageInstructions: '40 mg IV daily administered by registered nurse or doctor.',
        ),
        MedicineModel(
          id: 'med-023',
          name: 'Ceftron 1g IV',
          genericName: 'Ceftriaxone',
          category: 'Injection',
          manufacturer: 'Square Pharmaceuticals PLC',
          strength: '1 gm / vial',
          unit: 'Vial / Ampoule',
          price: 250.0,
          costPrice: 225.0,
          stockQuantity: 50,
          minStockAlert: 10,
          imageUrl: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=500&auto=format&fit=crop&q=80',
          requiresPrescription: true,
          description: 'Potent parenteral third-generation cephalosporin for severe hospital infections, meningitis, and septicemia.',
          dosageInstructions: '1-2 gm once daily via slow IV infusion after sensitivity test.',
        ),
        MedicineModel(
          id: 'med-024',
          name: 'Torax 30',
          genericName: 'Ketorolac Tromethamine',
          category: 'Injection',
          manufacturer: 'Incepta Pharmaceuticals Ltd.',
          strength: '30 mg / ml',
          unit: 'Vial / Ampoule',
          price: 75.0,
          costPrice: 67.5,
          stockQuantity: 35,
          minStockAlert: 10,
          imageUrl: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=500&auto=format&fit=crop&q=80',
          requiresPrescription: true,
          description: 'Short-term management of moderate to severe acute postoperative pain.',
          dosageInstructions: '30 mg administered IM or IV every 6 hours as needed (maximum 5 days).',
        ),
        MedicineModel(
          id: 'med-025',
          name: 'Xorim 750 Injection',
          genericName: 'Cefuroxime',
          category: 'Injection',
          manufacturer: 'Incepta Pharmaceuticals Ltd.',
          strength: '750 mg / vial',
          unit: 'Vial / Ampoule',
          price: 140.0,
          costPrice: 126.0,
          stockQuantity: 30,
          minStockAlert: 8,
          imageUrl: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=500&auto=format&fit=crop&q=80',
          requiresPrescription: true,
          description: 'Second-generation cephalosporin injection for surgical prophylaxis and serious respiratory infections.',
          dosageInstructions: '750 mg IM/IV 3 times daily as prescribed by doctor.',
        ),
        MedicineModel(
          id: 'med-026',
          name: 'Pevisone Cream',
          genericName: 'Econazole Nitrate + Triamcinolone Acetonide',
          category: 'Ointment / Cream',
          manufacturer: 'Synovia Pharma PLC (Formerly Sanofi)',
          strength: '1% + 0.1% (10 gm)',
          unit: 'Tube',
          price: 70.0,
          costPrice: 63.0,
          stockQuantity: 85,
          minStockAlert: 15,
          imageUrl: 'https://images.unsplash.com/photo-1608248597359-2ff96d859424?w=500&auto=format&fit=crop&q=80',
          requiresPrescription: false,
          description: 'Dual-action antifungal and anti-inflammatory cream for eczema with fungal infection, tinea, and ringworm.',
          dosageInstructions: 'Apply sparingly to affected skin twice daily morning and evening.',
        ),
        MedicineModel(
          id: 'med-027',
          name: 'Aclo Gel',
          genericName: 'Aceclofenac',
          category: 'Ointment / Cream',
          manufacturer: 'Incepta Pharmaceuticals Ltd.',
          strength: '1.5% (15 gm)',
          unit: 'Tube',
          price: 60.0,
          costPrice: 54.0,
          stockQuantity: 70,
          minStockAlert: 12,
          imageUrl: 'https://images.unsplash.com/photo-1608248597359-2ff96d859424?w=500&auto=format&fit=crop&q=80',
          requiresPrescription: false,
          description: 'Topical NSAID gel for localized muscular sprains, joint strains, back pain, and tendonitis.',
          dosageInstructions: 'Gently massage into the painful area 3 times daily.',
        ),
        MedicineModel(
          id: 'med-028',
          name: 'Neocort Ointment',
          genericName: 'Neomycin Sulfate + Hydrocortisone Acetate',
          category: 'Ointment / Cream',
          manufacturer: 'Square Pharmaceuticals PLC',
          strength: '5mg + 10mg / gm (5 gm)',
          unit: 'Tube',
          price: 40.0,
          costPrice: 36.0,
          stockQuantity: 65,
          minStockAlert: 12,
          imageUrl: 'https://images.unsplash.com/photo-1608248597359-2ff96d859424?w=500&auto=format&fit=crop&q=80',
          requiresPrescription: false,
          description: 'Antibiotic plus corticosteroid ointment for inflammatory dermatoses prone to bacterial infection.',
          dosageInstructions: 'Apply thin layer to the affected area 2 to 3 times daily.',
        ),
        MedicineModel(
          id: 'med-029',
          name: 'Burnsil Cream',
          genericName: 'Silver Sulfadiazine',
          category: 'Ointment / Cream',
          manufacturer: 'Square Pharmaceuticals PLC',
          strength: '1% (25 gm)',
          unit: 'Tube',
          price: 65.0,
          costPrice: 58.5,
          stockQuantity: 60,
          minStockAlert: 10,
          imageUrl: 'https://images.unsplash.com/photo-1608248597359-2ff96d859424?w=500&auto=format&fit=crop&q=80',
          requiresPrescription: false,
          description: 'Topical antimicrobial cream for prevention and treatment of burn wound infections.',
          dosageInstructions: 'Apply 1-2 mm thick layer over clean burned area 1-2 times daily with sterile gloves.',
        ),
        MedicineModel(
          id: 'med-030',
          name: 'Mupirocin Ointment',
          genericName: 'Mupirocin',
          category: 'Ointment / Cream',
          manufacturer: 'Beximco Pharmaceuticals PLC',
          strength: '2% (10 gm)',
          unit: 'Tube',
          price: 120.0,
          costPrice: 108.0,
          stockQuantity: 50,
          minStockAlert: 10,
          imageUrl: 'https://images.unsplash.com/photo-1608248597359-2ff96d859424?w=500&auto=format&fit=crop&q=80',
          requiresPrescription: true,
          description: 'Topical antibacterial ointment for impetigo, folliculitis, and traumatic secondary skin infections.',
          dosageInstructions: 'Apply small quantity to affected area 3 times daily for up to 10 days.',
        ),
        MedicineModel(
          id: 'med-031',
          name: 'Tobracin Eye Drops',
          genericName: 'Tobramycin',
          category: 'Eye & Ear Drops',
          manufacturer: 'OSL Pharma Limited',
          strength: '0.3%',
          unit: 'Bottle (5ml)',
          price: 100.0,
          costPrice: 90.0,
          stockQuantity: 55,
          minStockAlert: 10,
          imageUrl: 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?w=500&auto=format&fit=crop&q=80',
          requiresPrescription: true,
          description: 'Aminoglycoside ophthalmic solution for external bacterial infections of the eye and surrounding tissue.',
          dosageInstructions: 'Instill 1 to 2 drops into affected eye(s) every 4 hours.',
        ),
        MedicineModel(
          id: 'med-032',
          name: 'Naphcon-A Eye Drops',
          genericName: 'Naphazoline Hydrochloride + Pheniramine Maleate',
          category: 'Eye & Ear Drops',
          manufacturer: 'Alcon Laboratories / Local Importers',
          strength: '0.025% + 0.3%',
          unit: 'Bottle (15ml)',
          price: 280.0,
          costPrice: 260.0,
          stockQuantity: 40,
          minStockAlert: 8,
          imageUrl: 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?w=500&auto=format&fit=crop&q=80',
          requiresPrescription: false,
          description: 'Dual action decongestant and antihistaminic ophthalmic solution for allergic conjunctivitis, itching, and redness.',
          dosageInstructions: 'Instill 1-2 drops into affected eye up to 4 times daily.',
        ),
        MedicineModel(
          id: 'med-033',
          name: 'Moxison Eye Drops',
          genericName: 'Moxifloxacin',
          category: 'Eye & Ear Drops',
          manufacturer: 'Incepta Pharmaceuticals Ltd.',
          strength: '0.5%',
          unit: 'Bottle (5ml)',
          price: 140.0,
          costPrice: 126.0,
          stockQuantity: 50,
          minStockAlert: 10,
          imageUrl: 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?w=500&auto=format&fit=crop&q=80',
          requiresPrescription: true,
          description: 'Fourth-generation fluoroquinolone ophthalmic antibiotic for bacterial conjunctivitis.',
          dosageInstructions: '1 drop in the affected eye 3 times daily for 7 days.',
        ),
        MedicineModel(
          id: 'med-034',
          name: 'Optachlor Eye Drops',
          genericName: 'Chloramphenicol',
          category: 'Eye & Ear Drops',
          manufacturer: 'Square Pharmaceuticals PLC',
          strength: '0.5%',
          unit: 'Bottle (5ml)',
          price: 40.0,
          costPrice: 36.0,
          stockQuantity: 75,
          minStockAlert: 15,
          imageUrl: 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?w=500&auto=format&fit=crop&q=80',
          requiresPrescription: true,
          description: 'Broad-spectrum antibacterial eye drop for superficial ocular infections.',
          dosageInstructions: '1 to 2 drops every 2 hours initially, reducing frequency as infection resolves.',
        ),
        MedicineModel(
          id: 'med-035',
          name: 'Latanest Eye Drops',
          genericName: 'Latanoprost',
          category: 'Eye & Ear Drops',
          manufacturer: 'Incepta Pharmaceuticals Ltd.',
          strength: '50 mcg / ml',
          unit: 'Bottle (2.5ml)',
          price: 450.0,
          costPrice: 405.0,
          stockQuantity: 30,
          minStockAlert: 6,
          imageUrl: 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?w=500&auto=format&fit=crop&q=80',
          requiresPrescription: true,
          description: 'Prostaglandin analogue ophthalmic solution for reducing elevated intraocular pressure in open-angle glaucoma.',
          dosageInstructions: '1 drop in affected eye(s) once daily in the evening.',
        ),
        MedicineModel(
          id: 'med-036',
          name: 'Azmasol Inhaler',
          genericName: 'Salbutamol',
          category: 'Inhaler',
          manufacturer: 'Beximco Pharmaceuticals PLC',
          strength: '100 mcg / puff',
          unit: 'Piece (200 Puffs)',
          price: 250.0,
          costPrice: 225.0,
          stockQuantity: 65,
          minStockAlert: 15,
          imageUrl: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=500&auto=format&fit=crop&q=80',
          requiresPrescription: true,
          description: 'Fast-acting bronchodilator reliever inhaler for acute asthma attack, wheezing, and bronchospasm.',
          dosageInstructions: '1 to 2 puffs for relief of acute symptoms. Maximum 8 puffs daily.',
        ),
        MedicineModel(
          id: 'med-037',
          name: 'Decomit 250 Inhaler',
          genericName: 'Beclometasone Dipropionate',
          category: 'Inhaler',
          manufacturer: 'Incepta Pharmaceuticals Ltd.',
          strength: '250 mcg / puff',
          unit: 'Piece (200 Puffs)',
          price: 320.0,
          costPrice: 288.0,
          stockQuantity: 45,
          minStockAlert: 10,
          imageUrl: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=500&auto=format&fit=crop&q=80',
          requiresPrescription: true,
          description: 'Inhaled prophylactic corticosteroid for regular maintenance prevention of chronic asthma.',
          dosageInstructions: '1 to 2 puffs twice daily morning and evening. Rinse mouth after inhalation.',
        ),
        MedicineModel(
          id: 'med-038',
          name: 'Windel Inhaler',
          genericName: 'Salbutamol',
          category: 'Inhaler',
          manufacturer: 'Square Pharmaceuticals PLC',
          strength: '100 mcg / puff',
          unit: 'Piece (200 Puffs)',
          price: 240.0,
          costPrice: 216.0,
          stockQuantity: 50,
          minStockAlert: 10,
          imageUrl: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=500&auto=format&fit=crop&q=80',
          requiresPrescription: true,
          description: 'Selective beta-2 adrenoreceptor agonist for prompt relief of asthma spasms and exercise-induced asthma.',
          dosageInstructions: '1-2 puffs as required for breathlessness.',
        ),
        MedicineModel(
          id: 'med-039',
          name: 'Ipratropium Inhaler',
          genericName: 'Ipratropium Bromide',
          category: 'Inhaler',
          manufacturer: 'Beximco Pharmaceuticals PLC',
          strength: '20 mcg / puff',
          unit: 'Piece (200 Puffs)',
          price: 300.0,
          costPrice: 270.0,
          stockQuantity: 35,
          minStockAlert: 8,
          imageUrl: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=500&auto=format&fit=crop&q=80',
          requiresPrescription: true,
          description: 'Anticholinergic bronchodilator for maintenance treatment of chronic obstructive pulmonary disease (COPD).',
          dosageInstructions: '1 to 2 puffs 3 to 4 times daily at regular intervals.',
        ),
        MedicineModel(
          id: 'med-040',
          name: 'Flutiform 125 Inhaler',
          genericName: 'Fluticasone Propionate + Formoterol Fumarate',
          category: 'Inhaler',
          manufacturer: 'Beximco Pharmaceuticals PLC',
          strength: '125 mcg + 5 mcg / puff',
          unit: 'Piece (120 Puffs)',
          price: 650.0,
          costPrice: 585.0,
          stockQuantity: 30,
          minStockAlert: 6,
          imageUrl: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=500&auto=format&fit=crop&q=80',
          requiresPrescription: true,
          description: 'Dual-component combination inhaler for regular management of persistent asthma and COPD.',
          dosageInstructions: '2 puffs twice daily in the morning and evening.',
        ),
        MedicineModel(
          id: 'med-041',
          name: 'Napa 500 Suppository',
          genericName: 'Paracetamol',
          category: 'Suppository',
          manufacturer: 'Beximco Pharmaceuticals PLC',
          strength: '500 mg',
          unit: 'Box (20 pcs)',
          price: 160.0,
          costPrice: 147.2,
          stockQuantity: 50,
          minStockAlert: 10,
          imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80',
          requiresPrescription: false,
          description: 'Rectal antipyretic suppository for adults unable to take oral medication due to severe vomiting or nausea.',
          dosageInstructions: 'Insert 1 suppository rectally every 4-6 hours as needed.',
        ),
        MedicineModel(
          id: 'med-042',
          name: 'Ace 250 Suppository',
          genericName: 'Paracetamol',
          category: 'Suppository',
          manufacturer: 'Square Pharmaceuticals PLC',
          strength: '250 mg',
          unit: 'Box (20 pcs)',
          price: 120.0,
          costPrice: 108.0,
          stockQuantity: 55,
          minStockAlert: 12,
          imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80',
          requiresPrescription: false,
          description: 'Pediatric rectal suppository for high fever and pain when oral administration is not tolerated.',
          dosageInstructions: 'Insert 1 suppository rectally based on child age/weight 3 to 4 times daily.',
        ),
        MedicineModel(
          id: 'med-043',
          name: 'Clofenac 50 Suppository',
          genericName: 'Diclofenac Sodium',
          category: 'Suppository',
          manufacturer: 'Square Pharmaceuticals PLC',
          strength: '50 mg',
          unit: 'Box (10 pcs)',
          price: 70.0,
          costPrice: 63.0,
          stockQuantity: 60,
          minStockAlert: 12,
          imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80',
          requiresPrescription: true,
          description: 'Rectal NSAID suppository for rapid relief of acute inflammatory arthritis, renal colic, and postoperative pain.',
          dosageInstructions: 'Insert 1 suppository into rectum 2 to 3 times daily.',
        ),
        MedicineModel(
          id: 'med-044',
          name: 'Diclomax 100 Suppository',
          genericName: 'Diclofenac Sodium',
          category: 'Suppository',
          manufacturer: 'Incepta Pharmaceuticals Ltd.',
          strength: '100 mg',
          unit: 'Box (10 pcs)',
          price: 100.0,
          costPrice: 90.0,
          stockQuantity: 45,
          minStockAlert: 10,
          imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80',
          requiresPrescription: true,
          description: 'High-strength diclofenac suppository for nocturnal pain in osteoarthritis and ankylosing spondylitis.',
          dosageInstructions: '1 suppository rectally at bedtime as prescribed.',
        ),
        MedicineModel(
          id: 'med-045',
          name: 'Glycerol Suppository Adult',
          genericName: 'Glycerin',
          category: 'Suppository',
          manufacturer: 'JMI Syringes & Medical Devices Ltd.',
          strength: '2.30 gm / pc',
          unit: 'Box (10 pcs)',
          price: 90.0,
          costPrice: 81.0,
          stockQuantity: 70,
          minStockAlert: 15,
          imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80',
          requiresPrescription: false,
          description: 'Hyperosmotic laxative rectal suppository providing fast and gentle relief from acute constipation.',
          dosageInstructions: 'Insert 1 suppository rectally and retain for 15-30 minutes until bowel action occurs.',
        ),
        MedicineModel(
          id: 'med-046',
          name: 'Bionime GM700',
          genericName: 'Glucose Monitoring Test Strip',
          category: 'Healthcare & Device',
          manufacturer: 'Bionime Corporation / Local Importer',
          strength: 'Test Strip Accessory',
          unit: 'Box (50 Strips)',
          price: 1100.0,
          costPrice: 990.0,
          stockQuantity: 35,
          minStockAlert: 8,
          imageUrl: 'https://images.unsplash.com/photo-1615461066841-6116e61058f4?w=500&auto=format&fit=crop&q=80',
          requiresPrescription: false,
          description: 'Noble metal electrode auto-coding blood glucose test strips for high precision diabetes monitoring.',
          dosageInstructions: 'Insert into Bionime meter with small blood droplet (0.75 μL).',
        ),
        MedicineModel(
          id: 'med-047',
          name: 'OneTouch Select Plus Strips',
          genericName: 'Glucose Test Strips',
          category: 'Healthcare & Device',
          manufacturer: 'Lifescan / Local Importer',
          strength: 'Test Strip Accessory',
          unit: 'Box (50 Strips)',
          price: 1250.0,
          costPrice: 1125.0,
          stockQuantity: 40,
          minStockAlert: 8,
          imageUrl: 'https://images.unsplash.com/photo-1615461066841-6116e61058f4?w=500&auto=format&fit=crop&q=80',
          requiresPrescription: false,
          description: 'ColorSure technology test strips for instant 5-second blood sugar level testing.',
          dosageInstructions: 'Use with OneTouch Select Plus meter as directed.',
        ),
        MedicineModel(
          id: 'med-048',
          name: 'Microlife BP A2 Basic',
          genericName: 'Digital Blood Pressure Monitor',
          category: 'Healthcare & Device',
          manufacturer: 'Microlife AG / Local Importer',
          strength: 'Medical Device',
          unit: 'Piece',
          price: 3200.0,
          costPrice: 2880.0,
          stockQuantity: 20,
          minStockAlert: 5,
          imageUrl: 'https://images.unsplash.com/photo-1615461066841-6116e61058f4?w=500&auto=format&fit=crop&q=80',
          requiresPrescription: false,
          description: 'Clinically validated upper-arm digital blood pressure monitor with Gentle+ cuff inflation and arrhythmia detection.',
          dosageInstructions: 'Apply cuff around upper arm at heart level and press Power button while seated.',
        ),
        MedicineModel(
          id: 'med-049',
          name: 'Omron NE-C28',
          genericName: 'Compressor Nebulizer',
          category: 'Healthcare & Device',
          manufacturer: 'Omron Healthcare / Local Importer',
          strength: 'Respiratory Device',
          unit: 'Piece',
          price: 4500.0,
          costPrice: 4050.0,
          stockQuantity: 15,
          minStockAlert: 4,
          imageUrl: 'https://images.unsplash.com/photo-1615461066841-6116e61058f4?w=500&auto=format&fit=crop&q=80',
          requiresPrescription: false,
          description: 'Heavy-duty compressor nebulizer with Virtual Valve Technology (V.V.T.) for respiratory therapy.',
          dosageInstructions: 'Pour physician-prescribed respiratory medication into chamber and breathe through mask/mouthpiece.',
        ),
        MedicineModel(
          id: 'med-050',
          name: 'JMI Disposable Syringe 5ml',
          genericName: 'Hypodermic Syringe with Needle',
          category: 'Healthcare & Device',
          manufacturer: 'JMI Syringes & Medical Devices Ltd.',
          strength: '5 ml / 22G Needle',
          unit: 'Box (100 Pcs)',
          price: 500.0,
          costPrice: 430.0,
          stockQuantity: 45,
          minStockAlert: 10,
          imageUrl: 'https://images.unsplash.com/photo-1615461066841-6116e61058f4?w=500&auto=format&fit=crop&q=80',
          requiresPrescription: false,
          description: 'Non-toxic, pyrogen-free, sterile single-use disposable syringes with sharp stainless steel needles.',
          dosageInstructions: 'For single parenteral injection use only by clinical personnel.',
        ),
        MedicineModel(
          id: 'med-051',
          name: 'Ostecal D',
          genericName: 'Calcium Carbonate + Vitamin D3',
          category: 'Vitamins & Supplements',
          manufacturer: 'Square Pharmaceuticals PLC',
          strength: '500 mg + 200 IU',
          unit: 'Box (30 pcs)',
          price: 240.0,
          costPrice: 216.0,
          stockQuantity: 80,
          minStockAlert: 15,
          imageUrl: 'https://images.unsplash.com/photo-1577401239170-897942555fb3?w=500&auto=format&fit=crop&q=80',
          requiresPrescription: false,
          description: 'Essential calcium and vitamin D3 supplement for bone mineral density, osteoporosis prevention, and joint strength.',
          dosageInstructions: '1 tablet once or twice daily with or after meals.',
        ),
        MedicineModel(
          id: 'med-052',
          name: 'Neuro-B',
          genericName: 'Vitamin B1 + B6 + B12',
          category: 'Vitamins & Supplements',
          manufacturer: 'Square Pharmaceuticals PLC',
          strength: '100mg + 200mg + 200mcg',
          unit: 'Box (30 pcs)',
          price: 300.0,
          costPrice: 270.0,
          stockQuantity: 85,
          minStockAlert: 15,
          imageUrl: 'https://images.unsplash.com/photo-1577401239170-897942555fb3?w=500&auto=format&fit=crop&q=80',
          requiresPrescription: false,
          description: 'High-potency neurotropic vitamin formulation for peripheral neuropathy, nerve regeneration, and numbness.',
          dosageInstructions: '1 to 3 tablets daily as prescribed by doctor.',
        ),
        MedicineModel(
          id: 'med-053',
          name: 'Filwel Gold',
          genericName: 'Multivitamin & Multimineral A-Z',
          category: 'Vitamins & Supplements',
          manufacturer: 'Square Pharmaceuticals PLC',
          strength: 'Adult Formulation',
          unit: 'Bottle (30 Pcs)',
          price: 360.0,
          costPrice: 324.0,
          stockQuantity: 90,
          minStockAlert: 15,
          imageUrl: 'https://images.unsplash.com/photo-1577401239170-897942555fb3?w=500&auto=format&fit=crop&q=80',
          requiresPrescription: false,
          description: 'Comprehensive daily micronutrient formulation with 32 essential vitamins and minerals for energy and vitality.',
          dosageInstructions: '1 tablet once daily after a main meal.',
        ),
        MedicineModel(
          id: 'med-054',
          name: 'Aristovit M',
          genericName: 'Multivitamin & Minerals',
          category: 'Vitamins & Supplements',
          manufacturer: 'Aristopharma Ltd.',
          strength: 'Standard Daily Spec',
          unit: 'Bottle (30 Pcs)',
          price: 150.0,
          costPrice: 135.0,
          stockQuantity: 75,
          minStockAlert: 15,
          imageUrl: 'https://images.unsplash.com/photo-1577401239170-897942555fb3?w=500&auto=format&fit=crop&q=80',
          requiresPrescription: false,
          description: 'Balanced daily multivitamin and mineral supplement to prevent nutritional deficiencies and boost immunity.',
          dosageInstructions: '1 tablet daily with breakfast.',
        ),
        MedicineModel(
          id: 'med-055',
          name: 'Bicozin Tablet',
          genericName: 'Zinc + Vitamin B Complex',
          category: 'Vitamins & Supplements',
          manufacturer: 'Square Pharmaceuticals PLC',
          strength: 'Zinc 20mg + Vitamin B',
          unit: 'Bottle (30 Pcs)',
          price: 180.0,
          costPrice: 162.0,
          stockQuantity: 95,
          minStockAlert: 20,
          imageUrl: 'https://images.unsplash.com/photo-1577401239170-897942555fb3?w=500&auto=format&fit=crop&q=80',
          requiresPrescription: false,
          description: 'Synergistic zinc and vitamin B complex supplement for hair, skin, nail health, immune defense, and tissue repair.',
          dosageInstructions: '1 tablet once daily with food.',
        ),
      ];
}